# Generated by Django 4.2.7 on 2026-09-29 08:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='next_run_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
