# Generated by Django 4.2.7 on 2026-09-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_transfer_content_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='notification_period',
            field=models.IntegerField(choices=[(1, '1 hour'), (3, '3 hours'), (6, '6 hours'), (12, '12 hours')]),
        ),
    ]
